export const aboutSection={
    id:"about",
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:"something about me",
    headLine:"enthusiastic, always eager to progress and learn new things",
    description:"i am a cheerful person, i play guitar, write plays, train martial arts",
    buttonLabel:"Contact me",
    imgStart:false,
    img: require("../../images/svg1.svg"),
    alt:"hobys",
    dark:true,
    primary:true,
    darkText:false,
}

export const myServices={
    id:"about",
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:"",
    headLine:"my goal is to become an elite front end",
    description:"I am looking for a place where I can use and improve my knowledge",
    buttonLabel:"Contact me",
    imgStart:true,
    img: require("../../images/svg2.svg"),
    alt:"myaim",
    dark:false,
    primary:false,
    darkText:true,
}

export const contact={
    id:"contact",
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:"",
    headLine:"please contact me",
    description:"I'm looking foward your contact",
    buttonLabel:"Send email",
    imgStart:true,
    img: require("../../images/social.svg"),
    alt:"social",
    dark:false,
    primary:false,
    darkText:false,
}

export const services={
    id:"services",
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:"i'm open for offers",
    headLine:"I invite you to go to my github and look for more works",
    description:"",
    buttonLabel:"Contact me",
    imgStart:true,
    img: require("../../images/services.svg"),
    alt:"services",
    dark:false,
    primary:false,
    darkText:false,
}